### PR TITLE
Add Surelog / UHDM sandbox applicaton

### PR DESCRIPTION
**Pull request by mgielda**
Signed-off-by: Michael Gielda <mgielda@antmicro.com>

### CODE REVIEW

**Comment by mgielda** [comment]
@alainmarcel - as discussed, this is the CHIPS Alliance application for your projects. Thank you for agreeing to do this! We will need your signoff here. I assume a comment with `Signed-off-by: Alain Dargelas <alain.dargelas@gmail.com>` will do.

**Comment by mgielda** [comment]
@brianwarner to confirm if my reasoning is correct,

**Comment by alaindargelas** [comment]
Signed-off-by: Alain Dargelas <alain.dargelas@gmail.com>

**Review by brianwarner — APPROVED** [review]
This looks great! Thanks for doing this, Alain and Michael!

**Comment by mgielda** [comment]
Hi @hcook - we will also need an approval from you I think, according to our procedure. Then we will be able to proceed to the final application and welcome Alain on board of the TSC!

**Review by hcook — APPROVED** [review]

**Comment by mgielda** [comment]
I approve as well

**Pull request merged**
