### PR TITLE
Refine the trademark commitment requirement.

### PR DESCRIPTION
**Pull request by mkdolan**
I've revised the trademark contribution language and suggest getting more specific on the obligation of the contributor.

### CODE REVIEW

**Comment by mgielda** [comment]
Thanks @mkdolan ! That's super helpful. What about people who apply for a trademark or register a domain after the fact? The language does not make it clear that we'd expect them to donate those things even if registered afterwards. Can we craft something that would somehow make that clear, so that people don't answer "N/A" and then change their mind?

**Comment by mkdolan** [comment]
@mgielda My intention with this phrasing is that they assign any rights to the name. They then wouldn't have the right to register a trademark later, after the fact, because any claim to a right would have been assigned away already. I think this is just a notice at this point - the real assignment happens in the contribution agreement we would sign with the contributor. Does that make sense?

**Comment by mgielda** [comment]
Ah, I see, that's what you mean with "common law". OK, I support this change then. We will have to retroactively ask all projects to say "yes" as well.

**Review by tgorochowik — APPROVED** [review]
+1

**Review by tmichalak — APPROVED** [review]
+1

**Pull request merged**
