### PR TITLE
Refactor the main README

### PR DESCRIPTION
**Pull request by mgielda**
This PR tidies up our README, and adds Alain to the TSC composition (this one is just a statement of fact, so the PR itself does not change governance). Normalized capitalization, added missing newline in one place, kept repetition to a minimum.

### CODE REVIEW

**Comment by mgielda** [comment]
+1 on my end.

@hzeller can you +1 this? or @alainmarcel, whoever is faster :)

**Comment by mgielda** [comment]
This one closes #51

**Comment by mgielda** [comment]
And also closes #56 with one stroke!

**Review by hcook — APPROVED** [review]

**Comment by mgielda** [comment]
OK, 2 TSC approvals, good to go!

**Pull request merged**
