### PR TITLE
Create application for VeeR

### PR DESCRIPTION
**Pull request by tmichalak**
Application for the VeeR project in .md format

### CODE REVIEW

**Comment by mgielda** [comment]
We will start the vote now. In the background, let's check if this data builds on the website, @tmichalak

**Comment by tmichalak** [comment]
Triggered a build on [veer-application-website-test](https://github.com/chipsalliance/tsc/tree/veer-application-website-test) branch. Website build job is on https://github.com/chipsalliance/chips-alliance-website/actions/runs/5324314036

**Comment by bensternthal** [comment]
Given the re-organization of the repository this file should now live here ```projects/project-data-files```

**Review by bensternthal — CHANGES_REQUESTED** [review]
This pr needs a few minor changes before merging, note this is due to updates we have made since this was filed:

- [ ] This file should live in this directory ```projects/project-data-files```
- [ ] Two items were added to the [template](https://github.com/chipsalliance/tsc/blob/main/projects/templates/project-application-template.yml):

```
communication_channels: "List project communication channels e.g. Slack, IRC, Mailing Lists"
financial_sponsorship: "Y/N - is there existing financial sponsorship of the project"```

**Comment by kgugala** [comment]
Updated the yaml to follow new template and moved it to the `project-data-files` directory

**Comment by mgielda** [comment]
OK, vote passed! @bensternthal could you pleas merge?

**Review by bensternthal — APPROVED** [review]

**Pull request merged**
